services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.0
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./example_logs:/example_logs  # Doit correspondre au chemin dans pipeline.conf
    depends_on:
      - elasticsearch
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5001:5001"
    volumes:
      - ./flask_app:/app
    depends_on:
      - elasticsearch 
  simulator:
    image: python:3.10-slim
    volumes:
      - ./example_logs:/app/logs    
      - ./flask_app/simulate_logs.py:/app/simulate_logs.py
    working_dir: /app
    command: ["python", "simulate_logs.py"]
    depends_on:
      - logstash


